### Create a post
POST localhost:8080/api/post
Content-Type: application/json

{
  "title": "Industrial Society and Its Consequences",
  "content": "Lorem Ipsum Dolor Sit Amet"
}

### Fetch a post (should return Industrial Society and Its Consequences)
GET localhost:8080/api/post/1

### Recommend some posts (randomly selected, for now)
GET localhost:8080/api/post

### Fetch a non-existent (*hopefully) post
GET localhost:8080/api/post/999999999